"""Abstract repository protocols for the departments aggregate."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from app.infrastructure.database.models.department import Department


class DepartmentRepository(Protocol):
    async def get_by_id(self, department_id: str) -> Department | None: ...
    async def get_by_code(self, code: str) -> Department | None: ...
    async def list_all(
        self,
        *,
        offset: int = 0,
        limit: int = 50,
        search: str | None = None,
    ) -> Sequence[Department]: ...
    async def count(self, *, search: str | None = None) -> int: ...
    async def create(self, department: Department) -> Department: ...
    async def update(self, department: Department) -> Department: ...
    async def get_children(self, parent_id: str) -> Sequence[Department]: ...
    async def has_active_employees(self, department_id: str) -> bool: ...
