"""Abstract repository protocols for the users aggregate."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from app.infrastructure.database.models.user import (
    PasswordResetToken,
    Permission,
    RefreshToken,
    Role,
    User,
)


class UserRepository(Protocol):
    async def get_by_id(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list_all(self, *, offset: int = 0, limit: int = 50) -> Sequence[User]: ...
    async def count(self) -> int: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...


class RoleRepository(Protocol):
    async def get_by_name(self, name: str) -> Role | None: ...
    async def get_by_id(self, role_id: str) -> Role | None: ...
    async def list_all(self) -> Sequence[Role]: ...
    async def create(self, role: Role) -> Role: ...
    async def upsert_by_name(self, name: str, description: str | None = None) -> Role: ...


class PermissionRepository(Protocol):
    async def get_by_code(self, code: str) -> Permission | None: ...
    async def list_all(self) -> Sequence[Permission]: ...
    async def upsert_by_code(self, code: str, description: str | None = None) -> Permission: ...


class RefreshTokenRepository(Protocol):
    async def create(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_token_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token_id: str, replaced_by: str | None = None) -> None: ...
    async def revoke_family(self, family_id: str) -> None: ...
    async def revoke_all_for_user(self, user_id: str) -> None: ...


class PasswordResetRepository(Protocol):
    async def create(self, token: PasswordResetToken) -> PasswordResetToken: ...
    async def get_by_token_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def mark_used(self, token_id: str) -> None: ...
    async def invalidate_all_for_user(self, user_id: str) -> None: ...
